# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

from . import reward_functions
from .anymal import (
    ACTION_DIM_ANYMAL,
    ACTION_OBS_OFFSET_ANYMAL,
    COMMAND_DIM_ANYMAL,
    COMMAND_OBS_OFFSET_ANYMAL,
    JOINT_POS_OBS_OFFSET_ANYMAL,
    JOINT_VEL_OBS_OFFSET_ANYMAL,
    OBS_DIM_ANYMAL,
    ConfigEnvAnymalPhoenX,
    EnvAnymalPhoenX,
    anymal_mirror_map_ppo,
)
from .env import (
    EnvPPO,
    capture_env_steps,
    collect_ppo_rollout,
    collect_ppo_rollout_seed_counter,
    make_seed_counter,
)
from .g1 import (
    ACTION_DIM_G1,
    OBS_DIM_G1,
    OBS_DIM_G1_ISAACLAB_FLAT,
    OBS_DIM_G1_NANOG1,
    ConfigEnvG1PhoenX,
    EnvG1PhoenX,
    g1_mirror_map_ppo,
)
from .go2 import ConfigEnvGo2PhoenX, EnvGo2PhoenX
from .humanoid import ACTION_DIM_HUMANOID, OBS_DIM_HUMANOID, ConfigEnvHumanoidPhoenX, EnvHumanoidPhoenX
from .networks import GaussianActor, PufferMinGRUNet, WarpMLP
from .optim import Adam, Muon
from .pbt import (
    ConfigPBT,
    GenerationResult,
    HparamSpec,
    ResultPBT,
    WorkerState,
    default_anymal_hparam_specs,
    default_g1_hparam_specs,
    population_based_train,
    population_based_train_anymal,
    population_based_train_g1,
)
from .ppo import (
    BufferRollout,
    ConfigPPO,
    MirrorMapPPO,
    StatsPPOUpdate,
    TrainerPPO,
    load_ppo_checkpoint,
    save_ppo_checkpoint,
)
from .sac import BatchSAC, BufferReplaySAC, ConfigSAC, StatsSACUpdate, TrainerSAC
from .toolbox import drop_ppo_checkpoint_inputs, insert_ppo_checkpoint_inputs, resize_ppo_checkpoint_inputs
from .training import (
    ConfigEvaluateAnymalPPO,
    ConfigEvaluateG1GatePPO,
    ConfigEvaluateG1PPO,
    ConfigEvaluateG1TargetPPO,
    ConfigTrainAnymalPPO,
    ConfigTrainG1PPO,
    ResultEvaluateAnymalPPO,
    ResultEvaluateG1GatePPO,
    ResultEvaluateG1PPO,
    ResultEvaluateG1TargetPPO,
    ResultTrainAnymalPPO,
    ResultTrainG1PPO,
    StatsEvaluateAnymalTargetPPO,
    StatsEvaluateG1GateCommandPPO,
    StatsEvaluateG1GatePPO,
    StatsEvaluateG1PPO,
    StatsEvaluateG1TargetPPO,
    StatsTrainAnymalPPO,
    StatsTrainG1PPO,
    evaluate_anymal_ppo,
    evaluate_g1_gate_ppo,
    evaluate_g1_ppo,
    evaluate_g1_target_ppo,
    train_anymal_ppo,
    train_g1_ppo,
)

__all__ = [
    "ACTION_DIM_ANYMAL",
    "ACTION_DIM_G1",
    "ACTION_DIM_HUMANOID",
    "ACTION_OBS_OFFSET_ANYMAL",
    "COMMAND_DIM_ANYMAL",
    "COMMAND_OBS_OFFSET_ANYMAL",
    "JOINT_POS_OBS_OFFSET_ANYMAL",
    "JOINT_VEL_OBS_OFFSET_ANYMAL",
    "OBS_DIM_ANYMAL",
    "OBS_DIM_G1",
    "OBS_DIM_G1_ISAACLAB_FLAT",
    "OBS_DIM_G1_NANOG1",
    "OBS_DIM_HUMANOID",
    "Adam",
    "BatchSAC",
    "BufferReplaySAC",
    "BufferRollout",
    "ConfigEnvAnymalPhoenX",
    "ConfigEnvG1PhoenX",
    "ConfigEnvGo2PhoenX",
    "ConfigEnvHumanoidPhoenX",
    "ConfigEvaluateAnymalPPO",
    "ConfigEvaluateG1GatePPO",
    "ConfigEvaluateG1PPO",
    "ConfigEvaluateG1TargetPPO",
    "ConfigPBT",
    "ConfigPPO",
    "ConfigSAC",
    "ConfigTrainAnymalPPO",
    "ConfigTrainG1PPO",
    "EnvAnymalPhoenX",
    "EnvG1PhoenX",
    "EnvGo2PhoenX",
    "EnvHumanoidPhoenX",
    "EnvPPO",
    "GaussianActor",
    "GenerationResult",
    "HparamSpec",
    "MirrorMapPPO",
    "Muon",
    "PufferMinGRUNet",
    "ResultEvaluateAnymalPPO",
    "ResultEvaluateG1GatePPO",
    "ResultEvaluateG1PPO",
    "ResultEvaluateG1TargetPPO",
    "ResultPBT",
    "ResultTrainAnymalPPO",
    "ResultTrainG1PPO",
    "StatsEvaluateAnymalTargetPPO",
    "StatsEvaluateG1GateCommandPPO",
    "StatsEvaluateG1GatePPO",
    "StatsEvaluateG1PPO",
    "StatsEvaluateG1TargetPPO",
    "StatsPPOUpdate",
    "StatsSACUpdate",
    "StatsTrainAnymalPPO",
    "StatsTrainG1PPO",
    "TrainerPPO",
    "TrainerSAC",
    "WarpMLP",
    "WorkerState",
    "anymal_mirror_map_ppo",
    "capture_env_steps",
    "collect_ppo_rollout",
    "collect_ppo_rollout_seed_counter",
    "default_anymal_hparam_specs",
    "default_g1_hparam_specs",
    "drop_ppo_checkpoint_inputs",
    "evaluate_anymal_ppo",
    "evaluate_g1_gate_ppo",
    "evaluate_g1_ppo",
    "evaluate_g1_target_ppo",
    "g1_mirror_map_ppo",
    "insert_ppo_checkpoint_inputs",
    "load_ppo_checkpoint",
    "make_seed_counter",
    "population_based_train",
    "population_based_train_anymal",
    "population_based_train_g1",
    "resize_ppo_checkpoint_inputs",
    "reward_functions",
    "save_ppo_checkpoint",
    "train_anymal_ppo",
    "train_g1_ppo",
]
